# Generated by Django 6.0.1 on 2026-01-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nids_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionresult',
            name='count',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
    ]
