# Generated by Django 6.0.1 on 2026-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nids_dashboard', '0002_remove_detectionresult_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionresult',
            old_name='detected_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='raw_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='severity',
            field=models.CharField(max_length=20),
        ),
    ]
