# Generated by Django 6.0.1 on 2026-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nids_dashboard', '0003_rename_detected_at_detectionresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
