# Generated by Django 6.0.1 on 2026-01-25 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nids_dashboard', '0004_alter_detectionresult_confidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='raw_data',
            field=models.TextField(blank=True, help_text='Original CSV row data', null=True),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useralertsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['attack_type'], name='nids_dashbo_attack__c0cb43_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['severity'], name='nids_dashbo_severit_3c57f9_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['created_at'], name='nids_dashbo_created_f7d569_idx'),
        ),
    ]
